### ISSUE TITLE
Migrate design system hosting from netlify to Amplify

### ISSUE THREAD

**Issue by chrisrhymes** [FutureNorthants/northants-design-system#540]
We can reduce the costs of hosting with Netlify by hosting with AWS Amplify instead. It offers the same functionality and offers previews too. 

This has been tested with the following pull request #539 

In the comments there is a link generated by AWS Amplify showing the preview link. 

## Tasks 
- [x] Register `https://design-system.westnorthants.gov.uk` as a custom domain in AWS Amplify and raise a halo ticket with the required DNS changes
- [ ] Create a PR to update the design system readme to point to the new url
- [x] Deactivate the netlify project and remove GitHub integration
- [x] Close down the netlify account to stop future payments.

**Comment by chrisrhymes** [comment]
I have raised a request to get the DNS changes made.

**Comment by chrisrhymes** [comment]
Amplify would not verify the DNS changes correctly. Forums suggest deleting the custom domain settings in Amplify completely and adding it again to try and resolve issues with DNS timeouts.

**Comment by chrisrhymes** [comment]
The design system has now been set up to run on https://design-system.westnorthants.gov.uk.

**Comment by chrisrhymes** [comment]
A pull request has been created to update the link in the readme file. 
https://github.com/FutureNorthants/northants-design-system/pull/549
